language: ruby

services:
  - docker

env:
  global:
    - IMAGE_NAME=andrewbell/ruby-dev
    - IMAGE_TAG=travis-${TRAVIS_BUILD_NUMBER}

before_install:
  - docker build -t ${IMAGE_NAME}:${IMAGE_TAG} .

deploy:
  provider: script
  script: bash docker_push
  on:
    branch: master
